version: "3.7"

services:
  # Core configuration
  php-fpm:
    container_name: php-fpm
    build:
      args:
        WORKFOLDER: "${WORKFOLDER}"
      context: .
      target: base
    ports:
      - '${PHP_PORT}:9000'
    volumes:
      - './:${WORKFOLDER}:rw'
      - './docker/php/conf/php.ini:/usr/local/etc/php/php.ini'
      # - './docker/php/conf/production/php.ini:/usr/local/etc/php/php.ini' -> Used for production.
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '${NGINX_PORT}:80'
    links:
      - php-fpm
    volumes:
      - './:${WORKFOLDER}:rw'
      - './docker/nginx/conf/core/nginx.conf:/etc/nginx/nginx.conf'
      - './docker/nginx/conf/development/docker-nginx.conf:/etc/nginx/conf.d/default.conf'
      # - './docker/nginx/conf/production/docker-nginx.conf:/etc/nginx/conf.d/default.conf' -> Uncomment this line for production.
      - './docker/nginx/logs/:/var/log/nginx'
    restart: always

  # DB configuration
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      MYSQL_DATABASE: '${MYSQL_DBNAME}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    volumes:
      - 'mysql:/var/lib/mysql'
    restart: always

  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - '${ADMINER_PORT}:8080'
    restart: always

volumes:
  mysql:
